FROM alpine


RUN apk add --no-cache tini su-exec
RUN set -x \
  && echo "===> Add malice user and malware folder..." \
  && addgroup malice \
  && adduser -S -G malice malice \
  && mkdir /malware \
  && chown -R malice:malice /malware

LABEL maintainer "https://github.com/blacktop"

LABEL malice.plugin.repository = "https://github.com/malice-plugins/clamav.git"
LABEL malice.plugin.category="av"
LABEL malice.plugin.mime="*"
LABEL malice.plugin.docker.engine="*"

COPY . /go/src/github.com/malice-plugins/clamav
RUN echo "export GO111MODULE=on" >> ~/.profile
RUN echo "export GOPROXY=https://goproxy.cn" >> ~/.profile
RUN source ~/.profile

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk --update add --no-cache clamav ca-certificates
RUN apk --update add --no-cache -t .build-deps \
  build-base \
  mercurial \
  musl-dev \
  openssl \
  bash \
  wget \
  git \
  gcc \
  go \
  && echo "Building avscan Go binary..." \
  && cd /go/src/github.com/malice-plugins/clamav \
  && export GOPATH=/go \
  && go version \
  && go get \
  && go build -ldflags "-s -w -X main.Version=v$(cat VERSION) -X main.BuildTime=$(date -u +%Y%m%d)" -o /bin/avscan \
  && rm -rf /go /usr/local/go /usr/lib/go /tmp/* \
  && apk del --purge .build-deps

# Update ClamAV Definitions
RUN mkdir -p /opt/malice \
  && chown malice /opt/malice \
  && freshclam

# Add EICAR Test Virus File to malware folder
ADD http://www.eicar.org/download/eicar.com.txt /malware/EICAR

RUN chown malice -R /malware

WORKDIR /malware

ENTRYPOINT ["/bin/avscan"]
CMD ["--help"]
